apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  selector:
    matchLabels:
      app: catalog
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: arunvashishtha/microservicewithmongo:1.1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          env:
            - name: DbSettings__Host
              valueFrom:
                configMapKeyRef:
                  key: host
                  name: mongodb-config
            - name: dbSettings__Password
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: mongodb-password
          livenessProbe:
            httpGet:
              path: /health/live
              port: 80
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  type: LoadBalancer
  selector:
    app: catalog
  ports:
    - port: 80
      targetPort: 80
